# -*- mode: ruby -*-
# vi: set ft=ruby :
# See README.md for details

#VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(2) do |config|

  config.vm.define "ubuntu-16"  do |ctl|
    ctl.vm.synced_folder '.', '/vagrant', disabled: true
    ctl.vm.box = "ubuntu/xenial64"
        ctl.vm.hostname = "ubuntu16"
        ctl.vm.network "private_network", ip: "172.31.0.100"
        ctl.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
        end
  end

  config.vm.define "rhel8"  do |web01|
    web01.vm.synced_folder '.', '/vagrant', disabled: true
    web01.vm.box = "generic/rhel8"
        web01.vm.hostname = "rhel8"
        web01.vm.network "private_network", ip: "172.31.0.101"
        web01.vm.provider "virtualbox" do |vb|
          vb.memory = 2024
        end
  end

  config.vm.define "ubuntu22"  do |web02|
    web02.vm.synced_folder '.', '/vagrant', disabled: true
    web02.vm.box = "bento/ubuntu-22.04"
        web02.vm.hostname = "ubuntu22"
        web02.vm.network "private_network", ip: "172.31.0.102"
        web02.vm.provider "virtualbox" do |vb|
          vb.memory = 2024
        end
  end
end

